### ISSUE TITLE
Abnormal number of epochs

### ISSUE THREAD

**Issue by sudy-super** [EleutherAI/gpt-neox#1018] opened 2023-08-27 17:43 UTC
**Describe the bug**
I was experimentally training a 125M model with a batch size of 4 and gradient_accumulation_steps of 1, which is the default value, for 20000 iters on a dataset with 59239 elements, and noticed that the number of epochs was an unusual number. I think 20000/(57403/4) ≈ 1.4 epochs. Perhaps my understanding is wrong, so please let me know.

**Log**
```
:
:
:
Using /root/.cache/torch_extensions/py310_cu118 as PyTorch extensions root...
No modifications detected for re-loaded extension module utils, skipping build step...
Loading extension module utils...
Time to load utils op: 0.0015444755554199219 seconds
[2023-08-27 15:57:44,086] [INFO] [engine.py:83:__init__] CONFIG: micro_batches=1 micro_batch_size=4
[2023-08-27 15:57:44,216] [INFO] [engine.py:138:__init__] RANK=0 STAGE=0 LAYERS=17 [0, 17) STAGE_PARAMS=171544320 (171.544M) TOTAL_PARAMS=171544320 (171.544M) UNIQUE_PARAMS=171544320 (171.544M)
 > number of parameters on model parallel rank 0: 171544320
 > total params: 171,544,320
[2023-08-27 15:57:44,224] [WARNING] [engine.py:2589:load_checkpoint] Unable to find latest file at /content/drive/MyDrive/gpt_neox_test/checkpoints/latest, if trying to load latest checkpoint please ensure this file exists or pass an explicit checkpoint tag when loading a checkpoint.
Unable to load checkpoint.
Loading checkpoint and starting from iteration 0
> building train, validation, and test datasets ...
    reading sizes...
    reading pointers...
    reading document index...
    creating numpy buffer of mmap...
    creating memory view of numpy buffer...
 > dataset split:
    train:
     document indices in [0, 57403) total of 57403 documents
    validation:
     document indices in [57403, 59180) total of 1777 documents
    test:
     document indices in [59180, 59239) total of 59 documents
 > WARNING: could not find index map files, building the indices on rank 0 ...
 > elapsed time to build and save doc-idx mapping (seconds): 0.071429
    using:
     number of documents:       57403
     number of epochs:          7
     sequence length:           4096
     total number of samples:   80401
 > elapsed time to build and save sample-idx mapping (seconds): 0.272192
 > elapsed time to build and save shuffle-idx mapping (seconds): 0.013910
 > loading doc-idx mapping from /content/drive/MyDrive/gpt_neox_test/essay_dataset/essay_dataset_text_document_train_indexmap_80000ns_4096sl_1234s_doc_idx.npy
 > loading sample-idx mapping from /content/drive/MyDrive/gpt_neox_test/essay_dataset/essay_dataset_text_document_train_indexmap_80000ns_4096sl_1234s_sample_idx.npy
 > loading shuffle-idx mapping from /content/drive/MyDrive/gpt_neox_test/essay_dataset/essay_dataset_text_document_train_indexmap_80000ns_4096sl_1234s_shuffle_idx.npy
    loaded indexed file in 0.011 seconds
    total number of samples: 80402
    total number of epochs: 7
 > WARNING: could not find index map files, building the indices on rank 0 ...
 > elapsed time to build and save doc-idx mapping (seconds): 0.019306
    using:
     number of documents:       1777
     number of epochs:          200
     sequence length:           4096
     total number of samples:   80059
> elapsed time to build and save sample-idx mapping (seconds): 0.006852
 > elapsed time to build and save shuffle-idx mapping (seconds): 0.030078
 > loading doc-idx mapping from /content/drive/MyDrive/gpt_neox_test/essay_dataset/essay_dataset_text_document_valid_indexmap_80040ns_4096sl_1234s_doc_idx.npy
 > loading sample-idx mapping from /content/drive/MyDrive/gpt_neox_test/essay_dataset/essay_dataset_text_document_valid_indexmap_80040ns_4096sl_1234s_sample_idx.npy
 > loading shuffle-idx mapping from /content/drive/MyDrive/gpt_neox_test/essay_dataset/essay_dataset_text_document_valid_indexmap_80040ns_4096sl_1234s_shuffle_idx.npy
    loaded indexed file in 0.011 seconds
    total number of samples: 80060
    total number of epochs: 200
 > WARNING: could not find index map files, building the indices on rank 0 ...
 > elapsed time to build and save doc-idx mapping (seconds): 0.007197
    using:
     number of documents:       59
     number of epochs:          3
     sequence length:           4096
     total number of samples:   48
 > elapsed time to build and save sample-idx mapping (seconds): 0.006254
 > elapsed time to build and save shuffle-idx mapping (seconds): 0.006600
 > loading doc-idx mapping from /content/drive/MyDrive/gpt_neox_test/essay_dataset/essay_dataset_text_document_test_indexmap_40ns_4096sl_1234s_doc_idx.npy
 > loading sample-idx mapping from /content/drive/MyDrive/gpt_neox_test/essay_dataset/essay_dataset_text_document_test_indexmap_40ns_4096sl_1234s_sample_idx.npy
 > loading shuffle-idx mapping from /content/drive/MyDrive/gpt_neox_test/essay_dataset/essay_dataset_text_document_test_indexmap_40ns_4096sl_1234s_shuffle_idx.npy
    loaded indexed file in 0.009 seconds
    total number of samples: 49
    total number of epochs: 3
setting training data start iteration to 0
setting validation data start iteration to 0
done with setups ..
:
:
:
```

**Environment:**
- Configs:
```
{
   # parallelism settings ( you will want to change these based on your cluster setup, ideally scheduling pipeline stages
   # across the node boundaries )
   "pipe_parallel_size": 1,
   "model_parallel_size": 1,

   # model settings
   "num_layers": 12,
   "hidden_size": 768,
   "num_attention_heads": 12,
   "seq_length": 4096,
   "max_position_embeddings": 4096,
   "norm": "rmsnorm",
   "rms_norm_epsilon": 1.0e-5,
   "pos_emb": "rotary",
   "no_weight_tying": true,
   "attention-config": [[["flash"], 12]],
   "gpt_j_residual": false,
   "output_layer_parallelism": "column",

   # these should provide some speedup but takes a while to build, set to true if desired
   "scaled_upper_triang_masked_softmax_fusion": false,
   "bias_gelu_fusion": false,
   "activation": "geglu",

   # init methods
   "init_method": "small_init",
   "output_layer_init_method": "wang_init",


   # optimizer settings
   "optimizer": {
     "type": "Adam",
     "params": {
       "lr": 0.0006,
       "betas": [0.9, 0.95],
       "eps": 1.0e-8,
     }
   },
   "min_lr": 0.00006,

   # for all zero_optimization options, see https://www.deepspeed.ai/docs/config-json/#zero-optimizations-for-fp16-training
   "zero_optimization": {
    "stage": 1,
    "allgather_partitions": True,
    "allgather_bucket_size": 500000000,
    "overlap_comm": True,
    "reduce_scatter": True,
    "reduce_bucket_size": 500000000,
    "contiguous_gradients": True,
  },

   # batch / data settings
   "train_micro_batch_size_per_gpu": 4,
   "data_impl": "mmap",

   # activation checkpointing
   "checkpoint_activations": true,
   "checkpoint_num_layers": 1,
   "partition_activations": true,
   "synchronize_each_layer": true,

   # regularization
   "gradient_clipping": 1.0,
   "weight_decay": 0.1,
   "hidden_dropout": 0.0,
   "attention_dropout": 0.0,

   # precision settings
   "fp16": {
     "enabled": true,
     "loss_scale": 0,
     "loss_scale_window": 1000,
     "hysteresis": 2,
     "min_loss_scale": 1
   },

   # misc. training settings
   "train_iters": 20000,
   "lr_decay_iters": 20000,
   "distributed_backend": "nccl",
   "lr_decay_style": "cosine",
   "warmup": 0.01,
   "checkpoint_factor": 1000,
   "eval_interval": 10,
   "eval_iters": 10,
   "save_iters": 500,

   # logging
   "log_interval": 100,
   "steps_per_print": 10,
   "keep_last_n_checkpoints": 4,
   "wall_clock_breakdown": true,

  #  networking
  "hostfile": "/mock_path"
}
```

**Comment by dashstander** [comment] 2023-09-13 19:13
Hey @sudy-super , the dataset generator splits up long documents into sequences of tokens and merges short documents based on the tokenizer and sequence length. So depending on the tokenizer and the length of your documents it will come out looking differently. [This](https://github.com/EleutherAI/gpt-neox/blob/43ea51c2f3aeef2fc642ba401ce08844eb5a0240/megatron/data/gpt2_dataset.py#L243) is where the number of epochs is calculated. It can be a little tough to reason about, but unless you can confirm that the total number of tokens is incorrect, this probably isn't a "bug".

**Comment by StellaAthena** [comment] 2023-11-25 23:09
Closing as abandoned and probably not a bug.

**Closed by StellaAthena** 2023-11-25 23:09 UTC
Labels: bug
