### ISSUE TITLE
Cannot finetune Enron example using 1-3B param model on 4x 3090's

### ISSUE THREAD

**Issue by FayZ676** [EleutherAI/gpt-neox#741] opened 2022-12-11 19:45 UTC
**The bug**
I assume that my system is more than capable of fine-tuning at the very least the 1-3B param model, but am new to NeoX and fine-tuning so I'm sure theres a few things I'm missing here.

`RuntimeError: Error(s) in loading state_dict for EmbeddingPipe:
	size mismatch for word_embeddings.weight: copying a param with shape torch.Size([25216, 6144]) from checkpoint, the shape in current model is torch.Size([50304, 2048]).`

**To Reproduce**
1. Download [Slim Weights](https://the-eye.eu/public/AI/models/GPT-NeoX-20B/slim_weights/)
2. Run `python prepare_data.py -d ./data -t HFTokenizer --vocab-file ./20B_checkpoints/20B_tokenizer.json`
3. Edit the `1-3B.yml` config file as seen in the screenshots below
4. Run `python ./deepy.py train.py -d configs 1-3B.yml`

**Screenshots**
1-3B.yml configuration
![Screen Shot 2022-12-11 at 11 41 56 AM](https://user-images.githubusercontent.com/94952795/206925492-a5930b87-dada-468d-9e62-6132f96a9ad9.png)
![Screen Shot 2022-12-11 at 11 42 09 AM](https://user-images.githubusercontent.com/94952795/206925497-05b83476-3adf-4353-a3ef-4037aca3c1b8.png)

**Environment (please complete the following information):**
 - GPUs: 4x 3090's

**Comment by StellaAthena** [comment] 2022-12-11 21:33
Closing as duplicate of https://github.com/EleutherAI/gpt-neox/issues/743

**Closed by StellaAthena** 2022-12-11 21:33 UTC
Labels: bug
