### ISSUE TITLE
Unreachable code and bug in if-else clause

### ISSUE THREAD

**Issue by tomsbergmanis** [EleutherAI/gpt-neox#1324] opened 2024-11-26 15:03 UTC
Hi @Quentin-Anthony, in your [merge](https://github.com/EleutherAI/gpt-neox/pull/1309), you broke the[ if clause](https://github.com/EleutherAI/gpt-neox/blame/a8f7913332cd220cff4ddacbb77e06cd5f5cc377/megatron/model/transformer.py#L1251) by making it evaluate a tuple, making some code unreachable. You should add an/or operator.  
![image](https://github.com/user-attachments/assets/ed5d07cf-c361-442b-a9f9-aff79b66bfb5)

**Comment by Quentin-Anthony** [comment] 2024-11-27 19:02
Looks like this wasn't caused by the merge, but rather: https://github.com/EleutherAI/gpt-neox/commit/dc4b81fe0e5286b395a4a4a65163ba4f4afb98af#diff-46c4c76deb18adf1de8e0be6d4229baed5f1f0308e141479f5a993b3d83dd445

Just fixed in #1325. Thanks for pointing this out, and apologies for not testing that one more thoroughly!

**Closed** 2024-11-27 19:04 UTC
Labels: bug
